# Generated by Django 5.0 on 2024-02-03 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicines',
            name='description',
            field=models.CharField(max_length=500),
        ),
    ]
